### ISSUE TITLE
[Bug]:  installation error

### ISSUE THREAD

**Issue by ahmadnajmdev** [afsakar/filament-translate-action#13]
### What happened?

composer require afsakar/filament-translate-action
>>
./composer.json has been updated
Running composer update afsakar/filament-translate-action
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires afsakar/filament-translate-action * -> satisfiable by afsakar/filament-translate-action[v0.1.0, v0.1.1, v0.1.2, v1.0.0, v1.0.1, v1.0.2].
    - afsakar/filament-translate-action[v0.1.0, ..., v0.1.2, v1.0.0, ..., v1.0.2] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.14] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require afsakar/filament-translate-action:*" to figure out if any version is installable, or "composer require afsakar/filament-translate-action:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### How to reproduce the bug

I don't know

### Package Version

lastest

### PHP Version

8.2.4

### Laravel Version

11

### Which operating systems does with happen with?

Windows

**Comment by afsakar** [comment]
Hi,

Thank you for your feedback. I fixed this error, Translate Action has Laravel 11 support now.
